<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>SpeechTranslatorDesktopPlus</AssemblyName>
    <OutputType>WinExe</OutputType>
    <Product>Speech Translator Desktop Plus</Product>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.7" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <ProjectReference Include="..\Shared\SpeechTranslatorShared.csproj" />
  </ItemGroup>

</Project>
